name: Continuous Integration

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure Cmake
      run: ./install_debs.sh && cmake --preset ci

    - name: Build Cmake
      run: cmake --build build -j4

    - name: Test
      working-directory: build
      run: ctest
